/*smc = instance_number(obj_explosion_small_e);
if (smc = 0)  vol = .4  * adj;
if (smc = 1)  vol = .4  * adj;
if (smc = 2)  vol = .35 * adj;
if (smc = 3)  vol = .33 * adj;
if (smc = 4)  vol = .31 * adj;
if (smc = 5)  vol = .29 * adj;
if (smc = 6)  vol = .26 * adj;
if (smc = 7)  vol = .23 * adj;
if (smc = 8)  vol = .2  * adj;
if (smc = 9)  vol = .16 * adj;
if (smc = 10) vol = .13 * adj;
if (smc = 11) vol = .1  * adj;
if (smc = 12) vol = .096* adj;
if (smc = 13) vol = .093* adj;
if (smc = 14) vol = .09 * adj;
if (smc = 15) vol = .086* adj;
if (smc = 16) vol = .083* adj;
if (smc = 17) vol = .08 * adj;
if (smc > 19) vol = .07 * adj;
audio_sound_gain(snd_explosion_small, vol, 810);*/
//sound_machine(snd_explosion_small, x, y);