if (!instance_exists(obj_tank_pilot)) exit;
var xxxx = 0; var yyyy = 0;
var dis1 = point_distance(obj_tank_pilot.x, obj_tank_pilot.y, xx - 0, yy + 576);
var dis2 = point_distance(obj_tank_pilot.x, obj_tank_pilot.y, xx + 0, yy - 576);
var dis3 = point_distance(obj_tank_pilot.x, obj_tank_pilot.y, xx + 576, yy + 0);
var dis4 = point_distance(obj_tank_pilot.x, obj_tank_pilot.y, xx - 576, yy - 0);
				dis = dis1;
if (dis < dis2) dis = dis2;
if (dis < dis3) dis = dis3;
if (dis < dis4) dis = dis4;
if (dis == dis1) yyyy += 576;
if (dis == dis2) yyyy -= 576;
if (dis == dis3) xxxx += 576;
if (dis == dis4) xxxx -= 576;
if (xxxx == xxx && yyyy == yyy) var spawner = obj_enemy_spawn;
else var spawner = obj_enemy_spawn_fast;
var spawn = instance_create_layer(xx + xxxx, yy + yyyy, "Enemy", spawner);
spawn.enemy = obj_enemy_mage_boss;
spawn.image_xscale = 2.5;
spawn.image_yscale = 2.5;