event_inherited();

//Subtracted by 9 * image_xscale because of empty pixels to the left of sprite
var ddir = direction + 180;
var xx = lengthdir_x((sprite_width / 2), ddir);
var yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_b, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction + 195;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_g, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction - 195;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_b, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction + 210;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_g, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction - 210;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_b, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction + 225;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_g, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction - 225;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_b, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction + 240;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_g, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction - 240;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_b, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction + 255;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_g, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction - 255;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_b, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction + 270;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_g, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction - 270;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_b, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction + 285;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_g, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction - 285;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_b, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction + 300;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_g, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction - 300;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_b, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction + 315;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_g, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction - 315;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_b, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction + 330;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_g, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction - 330;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_b, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction + 345;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_g, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction - 345;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_b, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);
	ddir = direction;
	xx = lengthdir_x((sprite_width / 2), ddir);
	yy = lengthdir_y((sprite_width / 2), ddir);
draw_sprite_ext(spr_enemy_spike_g, 0, x + xx, y + yy, image_xscale, image_yscale, ddir + 180, c_white, 1);