draw_self();
/*
var xi = lengthdir_x(30, direction + 180);
var yi = lengthdir_y(30, direction + 180);
var xxx = lengthdir_x(900, direction + 35);
var yyy = lengthdir_y(900, direction + 35);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(900, direction - 35);
yyy = lengthdir_y(900, direction - 35);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(900, direction + 25);
yyy = lengthdir_y(900, direction + 25);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(900, direction - 25);
yyy = lengthdir_y(900, direction - 25);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(900, direction + 15);
yyy = lengthdir_y(900, direction + 15);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(900, direction - 15);
yyy = lengthdir_y(900, direction - 15);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(900, direction + 0);
yyy = lengthdir_y(900, direction + 0);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
/*xxx = lengthdir_x(700, direction + 95);
yyy = lengthdir_y(700, direction + 95);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(700, direction - 95);
yyy = lengthdir_y(700, direction - 95);
draw_line(x + xi, y + yi, x + xxx, y + yyy);*/
/*
xxx = lengthdir_x(700, direction + 85);
yyy = lengthdir_y(700, direction + 85);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(700, direction - 85);
yyy = lengthdir_y(700, direction - 85);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(700, direction + 75);
yyy = lengthdir_y(700, direction + 75);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(700, direction - 75);
yyy = lengthdir_y(700, direction - 75);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(700, direction + 65);
yyy = lengthdir_y(700, direction + 65);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(700, direction - 65);
yyy = lengthdir_y(700, direction - 65);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(700, direction + 55);
yyy = lengthdir_y(700, direction + 55);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(700, direction - 55);
yyy = lengthdir_y(700, direction - 55);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(700, direction + 45);
yyy = lengthdir_y(700, direction + 45);
draw_line(x + xi, y + yi, x + xxx, y + yyy);
xxx = lengthdir_x(700, direction - 45);
yyy = lengthdir_y(700, direction - 45);
draw_line(x + xi, y + yi, x + xxx, y + yyy);